version: '3.8'

services:
  syncloudpos:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: syncloudpos_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      # Mount the prisma directory to host so the SQLite database is persistent across rebuilds
      - ./prisma:/app/prisma
    env_file:
      - .env
