version: '3.8'

services:
  syncloudpos:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: syncloudpos_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./prisma:/app/prisma
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: syncloudpos_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: syncloudpos_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
