[nginx-http-auth]
enabled = true

[nginx-limit-req]
enabled  = true
port     = http,https
logpath  = /var/log/nginx/syncloudpos-error.log

[sshd]
enabled  = true
port     = ssh
maxretry = 5
bantime  = 3600
findtime = 600
