const { PrismaClient } = require('@prisma/client');
const db = new PrismaClient();

async function main() {
    // 1. Clean up duplicate StockMovements for Purchase Orders
    const pos = await db.purchaseOrder.findMany({
        where: { status: { in: ["BON_LIVRAISON", "FACTURE", "COMPLETED"] } }
    });

    let deletedCount = 0;
    for (const po of pos) {
        const movements = await db.stockMovement.findMany({
            where: { referenceId: po.id, type: "PURCHASE" },
            orderBy: { createdAt: "asc" }
        });

        // Group by product
        const byProduct = {};
        for (const m of movements) {
            if (!byProduct[m.productId]) byProduct[m.productId] = [];
            byProduct[m.productId].push(m);
        }

        for (const productId in byProduct) {
            const mods = byProduct[productId];
            // If there are multiple movements for the same PO and product, keep only the latest one (the "Corrigé" one)
            if (mods.length > 1) {
                const toDelete = mods.slice(0, mods.length - 1);
                for (const m of toDelete) {
                    await db.stockMovement.delete({ where: { id: m.id } });
                    deletedCount++;
                }
            }
        }
    }
    console.log(`Deleted ${deletedCount} duplicate obsolete stock movements from edited POs.`);

    // 2. Re-calculate correct stock for ALL products to fix the STOCK ACTUEL mismatch!
    console.log("Recalculating correct true stock for all products based on transactions...");
    const products = await db.product.findMany({ include: { storeProducts: true } });

    let fixedProductsCount = 0;

    for (const product of products) {
        // Sum PO items
        const poItems = await db.purchaseOrderItem.findMany({
            where: { productId: product.id, purchaseOrder: { status: { in: ["BON_LIVRAISON", "FACTURE", "COMPLETED"] } } }
        });
        const poSum = poItems.reduce((acc, item) => acc + item.quantity, 0);

        // Sum SO items
        const soItems = await db.salesOrderItem.findMany({
            where: { productId: product.id, salesOrder: { status: { in: ["VALIDATED", "PAID"] } } }
        });
        const soSum = soItems.reduce((acc, item) => acc + item.quantity, 0);

        // Sum Client Returns
        const returns = await db.productReturn.findMany({
            where: { productId: product.id, status: "COMPLETED" }
        });
        const returnSum = returns.reduce((acc, item) => acc + item.quantity, 0);

        // Sum Supplier Returns
        const supReturns = await db.supplierReturn.findMany({
            where: { productId: product.id, status: "COMPLETED" }
        });
        const supReturnSum = supReturns.reduce((acc, item) => acc + item.quantity, 0);

        // Sum Manual Adjustments
        // Exclude those that are generated by other processes if possible.
        const manualAdjs = await db.stockMovement.findMany({
            where: { productId: product.id, type: "MANUAL_ADJUSTMENT" }
        });
        const manualSum = manualAdjs.reduce((acc, item) => acc + item.quantity, 0);

        const trueStock = manualSum + poSum - soSum + returnSum - supReturnSum;

        if (product.stock !== trueStock || (product.storeProducts[0] && product.storeProducts[0].stock !== trueStock)) {
            await db.product.update({
                where: { id: product.id },
                data: { stock: trueStock }
            });

            for (const sp of product.storeProducts) {
                await db.storeProduct.update({
                    where: { storeId_productId: { storeId: sp.storeId, productId: product.id } },
                    data: { stock: trueStock }
                });
            }
            fixedProductsCount++;
            if (product.name.includes("SMART WATCH NANO KIDS")) {
                console.log(`SMART WATCH NANO KIDS recalculated! Old Stock: ${product.stock}, New True Stock: ${trueStock}`);
                console.log(`Manual: ${manualSum}, PO: ${poSum}, SO: ${soSum}, RetClient: ${returnSum}, RetFour: ${supReturnSum}`);
            }
        }
    }

    console.log(`Fixed actual stock for ${fixedProductsCount} products!`);
}

main().finally(() => db.$disconnect());
